### ISSUE TITLE
Repeated `awaitFirst` poisons event type

### ISSUE THREAD

**Issue by kroltan** [MinnDevelopment/jda-reactor#5]
In an interactive workflow, I want to wait for the user to perform some action before proceeding.

So I write some code shaped like this:

```kotlin
val clickEvent = discord.on<ButtonClickEvent>()
    .filter { it.button?.id == authorizeButtonId }
    .awaitFirst()
```

However, this only works for the first `ButtonClickEvent`. For subsequent executions, this code throws:

```
Exception in thread "Thread-21" java.util.NoSuchElementException: No value received via onNext for awaitFirst
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.onComplete(Await.kt:270)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onComplete(FluxFilterFuseable.java:171)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onComplete(FluxMapFuseable.java:344)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onComplete(FluxFilterFuseable.java:391)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onComplete(FluxPeekFuseable.java:595)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.doComplete(FluxPublishOn.java:1094)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.checkTerminated(FluxPublishOn.java:1128)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:984)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
       at DiscordRoleAuthMe-1.0-SNAPSHOT-all.jar//reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:833)
```

Interestingly, I think this might have something to do with this being the _only_ subscription to this event.

If I put this code right after the JDA setup, before the snippet above has any chance to run...

```
discord.on<ButtonClickEvent>().subscribe()
```

Then it works flawlessly on every execution.

**Comment by MinnDevelopment** [comment]
Is this issue resolved with #6 ?

**Comment by kroltan** [comment]
I'm actually a big noob at the JVM scene, and only know how to specify dependencies from Maven, if that 😅 

Do you have a resource on how to set up a local/git/however dependency?

If not it's fine! Though I only have time to figure this out on the weekend.

**Comment by MinnDevelopment** [comment]
In your maven you can simply replace the version with `fbc9080` to load the specific commit since this repository is distributed through jitpack. It may timeout on first fetch since it has to build but you can just retry.

```xml
<dependency>
    <groupId>com.github.MinnDevelopment</groupId>
    <artifactId>jda-reactor</artifactId>
    <version>fbc9080</version>
</dependency>
```

**Comment by kroltan** [comment]
Oh, that's pretty cool, thank you!

---

Regarding the issue, it seems to still happen. The behaviour and error is the same, but the stacktrace is different probably because of the refactorings to my code, but I'll post it anyway in case it might be useful:

```
Exception in thread "Thread-20" java.util.NoSuchElementException: No value received via onNext for awaitFirst
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.onComplete(Await.kt:270)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onComplete(FluxFilter.java:300)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onComplete(FluxFilter.java:300)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.EmitterProcessor.subscribe(EmitterProcessor.java:217)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//reactor.core.publisher.Flux.subscribe(Flux.java:8469)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:190)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:183)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.reactive.AwaitKt.awaitFirst(Await.kt:24)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.DiscordAuthorizationMethod$authorize$clickEvent$1.invokeSuspend(DiscordAuthorizationMethod.kt:116)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.DiscordAuthorizationMethod$authorize$clickEvent$1.invoke(DiscordAuthorizationMethod.kt)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.DiscordAuthorizationMethod$authorize$clickEvent$1.invoke(DiscordAuthorizationMethod.kt)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.UtilsKt.withTimeout(Utils.kt:52)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.DiscordAuthorizationMethod.authorize(DiscordAuthorizationMethod.kt:112)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.DiscordAuthorizationMethod$authorize$1.invokeSuspend(DiscordAuthorizationMethod.kt)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:87)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:40)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.InteractiveLoginPlugin$onPlayerJoin$1.invoke(InteractiveLoginPlugin.kt:102)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//me.kroltan.interactivelogin.InteractiveLoginPlugin$onPlayerJoin$1.invoke(InteractiveLoginPlugin.kt:101)
       at InteractiveLogin-1.0-SNAPSHOT-all.jar//kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

(Everything shows up under my project's JAR because I'm using [Shadow](https://github.com/johnrengelman/shadow))

**Comment by MinnDevelopment** [comment]
Can you give me a minimal reproducible example that i can use to test this?

**Comment by kroltan** [comment]
Actually, I can. This also demonstrates it's not a problem with kotlinx.coroutines.reactor's `awaitFirst`:

Run the code and send a message to the bot. You will see nothing printed.

Now, do the same, but with the `sub.dispose()` line commented out, and it will work just fine!

```kotlin
fun main() {
    val discord = JDABuilder
        .createLight("YOUR BOT TOKEN HERE")
        .setEventManager(ReactiveEventManager())
        .build()

    var sub = Disposable {  }
    sub = discord.on<ReadyEvent>()
        .subscribe {
            sub.dispose()

            discord.on<MessageReceivedEvent>()
                .subscribe {
                    print(it.message.id)
                }
        }
}
```

Tested o Java 16 toolchain, with Kotlin targeting JVM 1.8, and just JDA and jda-reactor as dependencies.

**Comment by MinnDevelopment** [comment]
The code you provided works just fine, what am I supposed to observe here? It prints the messages without issue.

**Comment by MinnDevelopment** [comment]
I think this should be solved by 33f0e29

**Comment by kroltan** [comment]
That indeed does the trick! Thank you so much.

**Comment by kroltan** [comment]
By the way, (and sorry for the chatty comment) 

Thank you so much for this useful library and for your help! I hope you have a great day.
